<a href="https://colab.research.google.com/github/janubro0125/Varsha-S-S-Data-Science/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=[50,45,35,40,30]
a

[50, 45, 35, 40, 30]

In [ ]:
import numpy as np
mark=np.array(a)
mark

array([50, 45, 35, 40, 30])

In [ ]:
d=np.mean(mark)
d

np.float64(40.0)

In [ ]:
np.max(mark)

np.int64(50)

In [ ]:
np.min(mark)

np.int64(30)

In [ ]:
e=np.zeros([4,4])
e

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
f=np.ones([5,5])
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
g=np.eye(6)
g

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
h=np.linspace(1,20,10)
h

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
group=([1,2,6,2,4,5,3,5,4,6])
i=np.unique(group)
i

array([1, 2, 3, 4, 5, 6])

In [ ]:
j=np.array([9,5,7,3,1,6,2,8,4])
np.sort(j)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
k=np.array([[1,2,3],[4,5,6]])
l=np.array([[1,2],
           [3,4],
           [5,6]])
m=np.dot(k,l)
m

array([[22, 28],
       [49, 64]])

In [ ]:
n=np.array([[1,2],[3,4],[5,6]])
n.T

array([[1, 3, 5],
       [2, 4, 6]])

In [ ]:
o=np.array([1,2,3])
p=np.array([4,5,6])
np.concatenate((o,p))


array([1, 2, 3, 4, 5, 6])

In [ ]:
q=np.array([1,2,3,4,5])
r=np.array([6,7,8,9,0])
q+r

array([ 7,  9, 11, 13,  5])

In [ ]:
q-r

array([-5, -5, -5, -5,  5])

In [ ]:
q*r

array([ 6, 14, 24, 36,  0])

In [ ]:
s=np.random.rand(2,3)
s

array([[0.44813664, 0.92583106, 0.38006511],
       [0.67076979, 0.8669057 , 0.62875942]])

In [ ]:
t=np.array([9,5,7,3,1,6,2,8,4,0])
u=np.reshape(t,(2,5))
u

array([[9, 5, 7, 3, 1],
       [6, 2, 8, 4, 0]])

In [ ]:
v=np.arange(20).reshape(2,10)
v


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
w=np.array([9,5,7,3,1,6,2,8,4,0])
x=w[4:9]
x

array([1, 6, 2, 8, 4])

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
print(np.argmax(a))

4


In [3]:
print(np.argmin(a))

0


In [7]:
print(np.where(a>2))

(array([2, 3, 4]),)


In [9]:
print(np.cumsum(a))

[ 1  3  6 10 15]


In [12]:
a=np.array([1,2,3,4,5])
b=np.array([2,7,6,8,10])
print(np.corrcoef(a,b))

[[1.         0.90610304]
 [0.90610304 1.        ]]
